seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      log_model: true
      project: experiment
      save_dir:
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 250.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  detect_anomaly: true
model:
  lr: 1e-4
  use_ar_mlp: true
  qr: 0.0
  triangularity_loss: 0.0
  entropy: 0.0
  permute: false
  l1: 0.0
  budget: 0.0
  use_reverse: false
  use_batch_norm: false
  learnable_mask: false
  sinkhorn: false
  triangular: false
  verbose: false
  p: 1.0
  tau: 1.0
  alpha: 0.5
  box_min: 0.0
  box_max: 1.0
  sphere_r: 1.0
  normalization: ''
  start_step: null
  cholesky_permutation: false
data:
  n_mixing_layer: 1
  permute: false
  act_fct: leaky_relu
  use_sem: true
  data_gen_mode: rvs
  variant: 0
  nonlin_sem: false
  box_min: 0.0
  box_max: 1.0
  sphere_r: 1.0
  space_type: box
  m_p: 0
  c_p: 1
  m_param: 1.0
  c_param: 0.05
  batch_size: 6144
  latent_dim: 3
  normalize_latents: true
  use_dep_mat: true
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
notes: null
tags: null
ckpt_path: null
